version: '2'
services:
    app:
        image: dockerlapaz/votacion:1.0.0
        build: .
        ports:
            - 80:3000
        command: php -S 0.0.0.0:3000 -t /app
        volumes:
            - ./:/app
    redis:
        image: redis:3.0-alpine
